spring.application.name=pertemuan11
# Pastikan portnya 5432 untuk PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/praktikum_db
spring.datasource.username=postgres
spring.datasource.password=Cokiber_2893

# Perbaikan typo pada 'database-platform'
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
